### ISSUE TITLE
Mindy Weisberger (list add)

### ISSUE THREAD

**Issue by MindyWeisberger** [cgseife/mastodonpeople#11]
@laminda@mastodon.social 

I'm an editor and science writer at Live Science (additional bylines at Space.com and Scientific American) and podcast host of "Life's Little Mysteries"

**Comment by MindyWeisberger** [comment]
Thanks so much!

Best,

Mindy

• • •

Mindy Weisberger, science writer (she/her)
<https://www.scientificamerican.com/author/mindy-weisberger/>Bylines: Live
Science <https://www.livescience.com/author/mindy-weisberger>, Space.com
<https://www.space.com/author/mindy-weisberger>, Scientific American
<https://www.scientificamerican.com/author/mindy-weisberger/>
Podcast host: Life's Little Mysteries
<https://podcasts.apple.com/gb/podcast/lifes-little-mysteries/id1496044775>
Mobile: (201) 281-6587
Twitter: @laminda <https://twitter.com/LaMinda>

**Comment by cgseife** [comment]
My pleasure!
