### ISSUE TITLE
Becky Oskin

### ISSUE THREAD

**Issue by boskin1** [cgseife/mastodonpeople#17]
@boskin@mstdn.social

**Comment by cgseife** [comment]
Hi, Becky -- my apologies, but I'm making a distinction between journalists and PIOs for this list. The Google Docs journalism list isn't, as far as I know, so you won't be left totally homeless.  Sorry!

**Comment by boskin1** [comment]
That’s fair. I’m not asking you to change your mind, but I do want to
clarify that I’m not a PIO (I don’t pitch stories or work with reporters)
and I still freelance regularly.


Cheers,
Becky
