### ISSUE TITLE
Martin Enserink

### ISSUE THREAD

**Issue by cgseife** [cgseife/mastodonpeople#22]
@martinenserink@sciencemastodon.com

Michael Banks
@michaelbanks@sciencemastodon.com

**Comment by cgseife** [comment]
Virginia Heffernan
@virginiaheffernan@journa.host 

Dahlia lithwick
@Dahlialith@mstdn.social

Alex Boyd
@alexboyd@journa.host

**Comment by cgseife** [comment]
Delaney Dryfoos
@delaneydryfoos
judeisabella
@judeisabella

**Comment by p-pr** [comment]
Pratik Pawar
@pratik@mas.to
