### ISSUE TITLE
journa.host

### ISSUE THREAD

**Issue by adamjdavidson** [cgseife/mastodonpeople#24]
@adamdavidson@mastodon.social is now @adamdavidson@journa.host

pretty much all the 1,600 or so members of journa.host/public are journalists.

**Comment by cgseife** [comment]
Fixed your instance...

As for the journa.host instance -- true enough, but I can't hand-curate a list beyond a few hundred, and simple scraping doesn't really add value.

You're probably also aware that your population isn't all visible (or easily found) via journa.host/public or journa.host/explore, so it wouldn't be comprehensive anyway.

I'm probably going to stop updating this list soon, as it seems that journalists have achieved a critical mass and can find each other more easily now.

**Comment by adamjdavidson** [comment]
thank you!
